apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: react-webapp
  name: react-webapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: react-webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: react-webapp
    spec:
      containers:
      - image: reactnodecontainer.azurecr.io/react-node
        name: webapp
        imagePullPolicy: Always
        resources: {}
        env:
        - name: DB_HOST
          value: "aws-gcp-db.c5z6obx5ievu.us-east-2.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PSS
          value: "aws-gcp-db"
        - name: DB_DB
          value: "app"
        - name: PORT
          value: "9000"
        ports:
          - containerPort: 9000 
status: {}

